name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get GitHub Actions runner IP
        id: get_ip
        run: echo "IP=$(curl -s http://checkip.amazonaws.com)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Allow GitHub Actions IP in security group
        run: |
          IP=$(curl -s http://checkip.amazonaws.com)
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr $IP/32

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies and build frontend using Yarn
        run: |
          cd client  # React 프로젝트 경로로 이동
          yarn install
          yarn build:linux 

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build Spring Boot application
        run: |
          cd back  # Spring Boot 프로젝트 경로로 이동
          chmod +x gradlew
          ./gradlew clean build -x test
        env:
          TERM: xterm-256color  # 컬러 로그 출력을 위한 설정

      - name: List built files
        run: |
          ls -l back/build/libs/  # 빌드된 파일 확인 test

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" | base64 -d > $HOME/myweb2.pem
          chmod 400 $HOME/myweb2.pem
          scp -v -i $HOME/myweb2.pem -o StrictHostKeyChecking=no back/build/libs/back-0.0.1-SNAPSHOT.war ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/appReact.war
          ssh -v -i $HOME/myweb2.pem -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'bash ~/script2.sh'
        env:
          SSH_USER: ${{ secrets.SERVER_USER }}
          SSH_KNOWN_HOSTS: ${{ secrets.SERVER_HOST }}
          SSH_PEM_KEY: ${{ secrets.SERVER_SSH_KEY }}
